version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: proyecto-integrador
      MYSQL_USER: root
      MYSQL_PASSWORD: sasa
    restart: always
    networks:
      - spring
  proyecto-integrador-back:
    container_name: proyecto-integrador-back
    image: javiernicolasramos/proyecto-integrador-back:1.0
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: proyecto-integrador
      DB_USERNAME: root
      DB_PASSWORD: sasa
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8:3306/proyecto-integrador?allowPublicKeyRetrieval=false&autoReconnect=true&useSSL=false
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  proyecto-integrador-front:
    container_name: proyecto-integrador-front
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5174:4173"
    networks:
      - spring
    depends_on:
      - proyecto-integrador-back
    restart: always
networks:
  spring:
    name: spring
