import imagen1 from "../images/imagen1.jpg";
import imagen2 from "../images/imagen2.jpg";
import imagen3 from "../images/imagen3.jpg";
import guitarra from "../images/guitarra.png";


const productos = [
  {
    id: 1,
    nombre: "Producto 1",
    descripcion: "ed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed",
    precio: 2019.99,
    imagen: imagen1,
  },
  {
    id: 2,
    nombre: "Producto 2",
    descripcion: "Esta es la descripción del producto 2.",
    precio: 1129.99,
    imagen: guitarra,
  },
  {
    id: 3,
    nombre: "Producto 3",
    descripcion: "Esta es la descripción del producto 3.",
    precio: 3339.99,
    imagen: imagen3,
  },
  {
    id: 4,
    nombre: "Producto 4",
    descripcion: "Esta es la descripción del producto 4.",
    precio: 4449.99,
    imagen: imagen1,
  },
  {
    id: 5,
    nombre: "Producto 5",
    descripcion: "Esta es la descripción del producto 5.",
    precio: 3359.99,
    imagen: imagen2,
  },
  {
    id: 6,
    nombre: "Producto 6",
    descripcion: "Esta es la descripción del producto 6.",
    precio: 2269.99,
    imagen: imagen3,
  },
  {
    id: 7,
    nombre: "Producto 7",
    descripcion: "Esta es la descripción del producto 7.",
    precio: 3379.99,
    imagen: imagen1,
  },
  {
    id: 8,
    nombre: "Producto 8",
    descripcion: "Esta es la descripción del producto 8.",
    precio: 4489.99,
    imagen: imagen2,
  },
  {
    id: 9,
    nombre: "Producto 9",
    descripcion: "Esta es la descripción del producto 9.",
    precio: 1199.99,
    imagen: imagen3,
  },
  {
    id: 10,
    nombre: "Producto 10",
    descripcion: "Esta es la descripción del producto 10.",
    precio: 4109.99,
    imagen: imagen1,
  },
  {
    id: 11,
    nombre: "Producto 11",
    descripcion: "Esta es la descripción del producto 11.",
    precio: 3119.99,
    imagen: imagen2,
  },
  {
    id: 12,
    nombre: "Producto 12",
    descripcion: "Esta es la descripción del producto 12.",
    precio: 2129.99,
    imagen: imagen3,
  },
  {
    id: 13,
    nombre: "Producto 13",
    descripcion: "Esta es la descripción del producto 13.",
    precio: 1139.99,
    imagen: imagen1,
  },
  {
    id: 14,
    nombre: "Producto 14",
    descripcion: "Esta es la descripción del producto 14.",
    precio: 2149.99,
    imagen: imagen2,
  },
  {
    id: 15,
    nombre: "Producto 15",
    descripcion: "Esta es la descripción del producto 15.",
    precio: 4159.99,
    imagen: imagen3,
  },
  {
    id: 16,
    nombre: "Producto 16",
    descripcion: "Esta es la descripción del producto 16.",
    precio: 5169.99,
    imagen: imagen1,
  },
  {
    id: 17,
    nombre: "Producto 17",
    descripcion: "Esta es la descripción del producto 17.",
    precio: 6179.99,
    imagen: imagen2,
  },
  {
    id: 18,
    nombre: "Producto 18",
    descripcion: "Esta es la descripción del producto 18.",
    precio: 2189.99,
    imagen: imagen3,
  },
  {
    id: 19,
    nombre: "Producto 19",
    descripcion: "Esta es la descripción del producto 19.",
    precio: 2199.99,
    imagen: imagen1,
  },
  {
    id: 20,
    nombre: "Producto 20",
    descripcion: "Esta es la descripción del producto 20.",
    precio: 4209.99,
    imagen: imagen2,
  },
  {
    id: 21,
    nombre: "Producto 21",
    descripcion: "Esta es la descripción del producto 21.",
    precio: 2219.99,
    imagen: imagen3,
  },
  {
    id: 22,
    nombre: "Producto 22",
    descripcion: "Esta es la descripción del producto 22.",
    precio: 4229.99,
    imagen: imagen1,
  },
  {
    id: 23,
    nombre: "Producto 23",
    descripcion: "Esta es la descripción del producto 23.",
    precio: 5239.99,
    imagen: imagen2,
  },
  {
    id: 24,
    nombre: "Producto 24",
    descripcion: "Esta es la descripción del producto 24.",
    precio: 2249.99,
    imagen: imagen3,
  },
  {
    id: 25,
    nombre: "Producto 25",
    descripcion: "Esta es la descripción del producto 25.",
    precio: 4259.99,
    imagen: imagen1,
  },
  {
    id: 26,
    nombre: "Producto 26",
    descripcion: "Esta es la descripción del producto 26.",
    precio: 3269.99,
    imagen: imagen2,
  },
  {
    id: 27,
    nombre: "Producto 27",
    descripcion: "Esta es la descripción del producto 27.",
    precio: 5279.99,
    imagen: imagen3,
  },
  {
    id: 28,
    nombre: "Producto 28",
    descripcion: "Esta es la descripción del producto 28.",
    precio: 289.99,
    imagen: imagen1,
  },
  {
    id: 29,
    nombre: "Producto 29",
    descripcion: "Esta es la descripción del producto 29.",
    precio: 299.99,
    imagen: imagen2,
  },
  {
    id: 30,
    nombre: "Producto 30",
    descripcion: "Esta es la descripción del producto 30.",
    precio: 309.99,
    imagen: imagen3,
  },
];
  
  export default productos;